name: NoteAIPlus
bundleIdPrefix: com.noteaiplus
deploymentTarget:
  iOS: "16.0"

options:
  minimumXcodeGenVersion: 2.40.0
  generateEmptyDirectories: true
  createIntermediateGroups: true
  usesTabs: false
  indentWidth: 4
  tabWidth: 4

settings:
  base:
    DEVELOPMENT_TEAM: ""
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "16.0"
    TARGETED_DEVICE_FAMILY: "1"
    SUPPORTS_MACCATALYST: false
    ENABLE_USER_SCRIPT_SANDBOXING: false

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit
    from: 0.5.0
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: 5.8.0
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: 6.0.0
  SDWebImageSwiftUI:
    url: https://github.com/SDWebImage/SDWebImageSwiftUI
    from: 2.2.0
  RevenueCat:
    url: https://github.com/RevenueCat/purchases-ios
    from: 4.0.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.0.0
  Down:
    url: https://github.com/johnxnguyen/Down
    from: 0.11.0

targets:
  NoteAIPlus:
    type: application
    platform: iOS
    
    sources:
      - path: NoteAIPlus
        excludes:
          - "**/*.md"
    
    resources:
      - path: NoteAIPlus/Resources
        optional: true
    
    info:
      path: NoteAIPlus/App/Info.plist
      properties:
        CFBundleDisplayName: "NoteAI Plus"
        CFBundleIdentifier: "$(PRODUCT_BUNDLE_IDENTIFIER)"
        CFBundleName: "$(PRODUCT_NAME)"
        CFBundlePackageType: "APPL"
        CFBundleShortVersionString: "$(MARKETING_VERSION)"
        CFBundleVersion: "$(CURRENT_PROJECT_VERSION)"
        CFBundleExecutable: "$(EXECUTABLE_NAME)"
        LSRequiresIPhoneOS: true
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen:
          UIColorName: ""
          UIImageName: ""
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        NSMicrophoneUsageDescription: "このアプリは音声を録音して文字起こしを行うためにマイクへのアクセスが必要です。"
        NSCameraUsageDescription: "このアプリは画像や動画を撮影して記録するためにカメラへのアクセスが必要です。"
        NSPhotoLibraryUsageDescription: "このアプリは写真や動画を保存・読み込みするためにフォトライブラリへのアクセスが必要です。"
        NSDocumentsFolderUsageDescription: "このアプリは文書の保存・読み込みを行うためにDocumentsフォルダへのアクセスが必要です。"
        ITSAppUsesNonExemptEncryption: false
    
    dependencies:
      - package: WhisperKit
      - package: Alamofire
      - package: GRDB
        product: GRDB
      - package: SDWebImageSwiftUI
      - package: RevenueCat
        product: RevenueCat
      - package: Firebase
        product: FirebaseAuth
      - package: Firebase
        product: FirebaseFirestore
      - package: Firebase
        product: FirebaseStorage
      - package: Firebase
        product: FirebaseCrashlytics
      - package: Down
    
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.noteaiplus.app"
        INFOPLIST_FILE: "NoteAIPlus/App/Info.plist"
        SWIFT_OBJC_BRIDGING_HEADER: ""
        ENABLE_BITCODE: false
        OTHER_LDFLAGS: 
          - "-ObjC"
        FRAMEWORK_SEARCH_PATHS:
          - "$(inherited)"
          - "$(PLATFORM_DIR)/Developer/Library/Frameworks"
    
    preBuildScripts:
      - name: "SwiftLint"
        script: |
          if command -v swiftlint >/dev/null 2>&1
          then
              swiftlint
          else
              echo "warning: SwiftLint not installed, download from https://github.com/realm/SwiftLint"
          fi
        inputFiles:
          - "$(SRCROOT)/Carthage/Checkouts/SwiftLint/swiftlint"
        runOnlyWhenInstalling: false
    
    postBuildScripts:
      - name: "Firebase Crashlytics"
        script: |
          if [ -f "${PODS_ROOT}/FirebaseCrashlytics/run" ]; then
            "${PODS_ROOT}/FirebaseCrashlytics/run"
          fi
        inputFiles:
          - "$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)"

  NoteAIPlusTests:
    type: bundle.unit-test
    platform: iOS
    
    sources:
      - path: NoteAIPlusTests
        excludes:
          - "**/*.md"
    
    dependencies:
      - target: NoteAIPlus
    
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.noteaiplus.app.tests"
        INFOPLIST_FILE: ""
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        GENERATE_INFOPLIST_FILE: true

  NoteAIPlusUITests:
    type: bundle.ui-testing
    platform: iOS
    
    sources:
      - path: NoteAIPlusUITests
        excludes:
          - "**/*.md"
    
    dependencies:
      - target: NoteAIPlus
    
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: "com.noteaiplus.app.uitests"
        INFOPLIST_FILE: ""
        INFOPLIST_KEY_NSHumanReadableCopyright: ""
        GENERATE_INFOPLIST_FILE: true

schemes:
  NoteAIPlus:
    build:
      targets:
        NoteAIPlus: all
        NoteAIPlusTests: [test]
        NoteAIPlusUITests: [test]
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.SQLDebug": "1"
      environmentVariables:
        OS_ACTIVITY_MODE: "disable"
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - NoteAIPlus
      targets:
        - name: NoteAIPlusTests
          parallelizable: true
          randomExecutionOrder: true
        - name: NoteAIPlusUITests
          parallelizable: false
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release